### ISSUE TITLE
Server address should be placed in the airflow.cfg file

### ISSUE THREAD

**Issue by aarondeutsch** [turnerlabs/airflow_stacks#6]
In airflow.cfg, the following base_url should not be http://localhost:8080 but should instead be the actual IP/address of the server, so that links to log files, links in emails, etc work properly:

Previous:
[webserver]
auth_backend = airflow.contrib.auth.backends.password_auth
 The base url of your website as airflow cannot guess what domain or
 cname you are using. This is used in automated emails that
 airflow sends to point links to the right web server
base_url = http://localhost:8080

Proposed (I assume you can get the IP from an EIP?):

[webserver]
auth_backend = airflow.contrib.auth.backends.password_auth
 The base url of your website as airflow cannot guess what domain or
 cname you are using. This is used in automated emails that
 airflow sends to point links to the right web server
base_url = http://54.152.114.8:8080

**Comment by smithatlanta** [comment]
added with 1.10 changes
